### ISSUE TITLE
Add rollback for saving logs to Tempo

### ISSUE THREAD

**Issue by mikx98** [vacuumlabs/fine-tracker#101]
It happened to me, that all logs went fine (and were logged to Tempo) and one returned error. So we displayed error and I logged it again. This time with success, but almost everything was logged twice. Do it transaction-like.

**Comment by jakuub** [comment]
I think, that if we perform logging without emptying points and marking them as "synced", we can sync them point-by-point, and for those, which cause error, we can leave them not synced, so if we sync again, it will sync only not synced points - this should help to solve this issue.

**Comment by mikx98** [comment]
done in #115
