### ISSUE TITLE
Focus minutes after : typed into hour input

### ISSUE THREAD

**Issue by jakuub** [vacuumlabs/fine-tracker#107]
I am used to write time as `10:00` and if the typing of `:` will change focus to minutes, it will be perfect. 

This can be also great for someone used to tempo. Maybe.

**Comment by jakuub** [comment]
@mikx98 @Siegrift WDYT?

**Comment by Siegrift** [comment]
Agree.

**Comment by mikx98** [comment]
I am without opinion on this one, if it makes sense to you, let's make it sometime

**Comment by jakuub** [comment]
Resolved in new design
