### ISSUE TITLE
Select full hour input if editing time.

### ISSUE THREAD

**Issue by jakuub** [vacuumlabs/fine-tracker#109]
I often use manual typing of time to tasks, and it will be great, e.g. for retrospective logging, to have hour input "selected", to be able to directly write time.

**Comment by Siegrift** [comment]
Mhh, the input dialog should focus time by default. If not it is rather a big not a feature :) which broswer do you use @jakuub

**Comment by mikx98** [comment]
IMO this makes even bigger sense with the current new design @domiin50, if you have time :pray:

**Comment by jakuub** [comment]
Resolved by new design.
