### ISSUE TITLE
Speed dial without CTRL

### ISSUE THREAD

**Issue by jakuub** [vacuumlabs/fine-tracker#110]
I don't see reason in using CTRL for speed dial, if it can be only numbers.

**Comment by Siegrift** [comment]
I totally agree and wanted to persuade @mikx to adpot this :D

**Comment by mikx** [comment]
Haha, wrong **mikx**. I'm mikx**68**.

**Comment by jakuub** [comment]
@mikx98 what is the reason against this?

**Comment by mikx98** [comment]
just plain habit to have shortcuts associated with "special keys"
