### ISSUE TITLE
Better confirmation view when submitting

### ISSUE THREAD

**Issue by Siegrift** [vacuumlabs/fine-tracker#113]
I find it annoying the need to scroll down, and see the logs in calendar. I think it would be better to just display the logs in textual format like:
```
10:00 - 11:00 Issue XXX
12:00 - 14:00 Issue YYY
14:00 - 17:00 Issue ZZZ
17:00 - 19:00 Issue ABC
```

**Comment by mikx98** [comment]
maybe this issue will be closed by #115 as well

**Comment by mikx98** [comment]
done in #115

**Comment by Siegrift** [comment]
I would not mark it as done, I think that the content right now is not enough. I only see the total amount logged. I suppose there should be a button `show dietails`, which would show the calendar or my favourite AGENDA view :D so you can see what specificly is logged.

**Comment by mikx98** [comment]
okay :man_facepalming:

**Comment by mikx98** [comment]
the new upcoming design solves this, it is not relevant for us to address it until then
