### ISSUE TITLE
Double logging bug

### ISSUE THREAD

**Issue by hleumas** [vacuumlabs/fine-tracker#118]
It seems that I've encountered double logging bug.

I am not sure how has this happened, but it seems that today fine-tracker logged again stuff that I've logged 2 weeks ago.
<img width="204" alt="screenshot 2019-01-27 at 00 14 37" src="https://user-images.githubusercontent.com/357078/51793944-e8895180-21c8-11e9-84cf-47a0f283c110.png">

**Comment by mikx98** [comment]
@hleumas is there any chance that you encountered #101 issue? That would mean that it was logged twice in the past already, not after this Thursday (?)

**Comment by mikx98** [comment]
When you navigate to that date in current fine-tracker, do you see the logs there? That would mean that they were logged after this Thursday

**Comment by hleumas** [comment]
Well, it's very strange.

It seems that the worklogs were logged twice to Tempo:

on January 16th, and on January 26th.

They differ a bit. It seems that worklogs logged on January 16th are rounded to whole 15 min, while those logged on January 26th are exact. Other than that, the logs are the same.
