### ISSUE TITLE
Error when trying to log 2 timesheets into one task

### ISSUE THREAD

**Issue by jozefspisiak** [vacuumlabs/fine-tracker#119]
![fineerror](https://user-images.githubusercontent.com/1767146/51849392-e554a980-231f-11e9-984e-88cfb69f91ba.png)
Simple use case, trying to log both timesheets into kiwi-1 task, I got stuck on this error.

**Comment by mikx98** [comment]
@jozefspisiak closing as it really seems like #100 . If you encounter above problem again and refreshing the page doesn't help, feel free to reopen :)
