### ISSUE TITLE
Replace sign with JIRA for Github login

### ISSUE THREAD

**Issue by hleumas** [vacuumlabs/fine-tracker#126]
JIRA doesn't really support SSO. What this really does in practice is that it creates a new authorization token each time a person logs into fine tracker. This results in a pretty shitty user experience.

I suggest that we:

– implement login via Github
– one time authorization grant for JIRA / Tempo

Authorization tokens can be stored in database per user and accessed after the user logs in using their Github account.

# General Github signer

Given that this is not the only project with this problem, I have an even better suggestion. Let's create microservice that can provide SSO for all other vacuum apps.

Something that you'd be able to request github or atlassian token from, and it would handle everything for you. This might even simplify the authorization workflow for all the apps we manage.

**Comment by michal-lenik** [comment]
Just a note: there is no persistent database on now.sh so the DB would have to be somewhere outside. General Github signer might be a good idea.

**Comment by hleumas** [comment]
@michal-lenik we can use AWS hosted PostgreSQL.

**Comment by jakuub** [comment]
What about Auth0 - it can be used login through GitHub and also can store access tokens. It also can manage SSO  with automatic login if you are logged in elsewere. And it is free for up to 7000 active users.

It will need a small universal page to authorize Jira and tempo, but it should be easy to do and it can be derived from existing code-base in this project.

One potential problem can be, that tokens are stored on client-side, but I don't think it is a problem.

**Comment by hleumas** [comment]
I think @mpinter had some very good arguments against Auth0.

**Comment by mpinter** [comment]
Hi all - depends on the requirements, actually it may be a good fit in this case. What auth0 does well is easy integration with OAuth providers. If we don't really care that the login page will be a static page hosted outside of the app on auth0 servers, customisable only to some degree through the auth0 dashboard - which, I feel, we should not care about at all in this case - then I think it might be worth it.

The argument that still holds is, that unless they've worked on it hard for last half-a-year, the documentation is horrible.

**Comment by jakuub** [comment]
Ok, so maybe we can do it with Auth0:

* we can log in via GitHub or Google - we should choose, which one
* we can authorize to JIRA and Tempo in fine-tracker and store access token to Auth0 metadata
    * this can be changed later, but I prefer to authorize to a resource in the app which needs it, not globally once
* we can pass this tokens with requests to the server
* if we don't want to store raw access tokens in local storage, we can encrypt it by vacuum secret, which will be shared across internal applications. 


This way, there is no  need for aditional database, and the server can be stateless.

**Comment by hleumas** [comment]
@jakuub I've already created simple SSO service, no support for JIRA yet.
https://github.com/vacuumlabs/vlsso

However, I don't think it's much work to finish it and it might be bette than to rely on some 3rd party.

**Comment by hleumas** [comment]
Take a look at this:
https://github.com/vacuumlabs/pay-overview/commit/34e7dc53e6f6850f891038ddfb8d84dbf11cdc65

I've already implemented SSO for JIRA for pay overview.

**Comment by jakuub** [comment]
Thank you, we will get to it after the basic implementation of redesign. It should be soon:tm:
