### ISSUE TITLE
Order is not re-computed when logging retrospectively

### ISSUE THREAD

**Issue by mikx98** [vacuumlabs/fine-tracker#165]
exact steps to reproduce:
1. log something
2. save into tempo
3. add a log starting before the first log
4. be confused by the order of the worklogs :confused: 

![Screenshot from 2019-06-18 17-21-20](https://user-images.githubusercontent.com/22675674/59697358-f8441980-91ed-11e9-8b2d-173da3816fd5.png)

**Comment by jakuub** [comment]
:fearful:
