### ISSUE TITLE
I can create log with no description

### ISSUE THREAD

**Issue by MilanJimi** [vacuumlabs/fine-tracker#180]
1. Create a log with just time
2. It still appears in FineTracker. This might not yet be a problem
3. Assign an issue and try to save the log. 

Since Jira requires description for each log, the save will fail for this log

**Comment by mikx98** [comment]
Empty log is actually a very handy feature - to mark end of worklog and start of a worklog that you don't want to submit. For example you don't want to write `lunch` or `end of work`. The timeline even doesn't show such worklogs - I :heart: it personally. 

**So the only issue I see in this, is that you should not be able to assign an issue to empty-description worklog.**

**Comment by domiin50** [comment]
Would like to keep this issue open till the sidebar with issue input will be finally properly implemented. Issue input will be disabled when the worklog has no description. It is pointless to handle it in action imo.

Meanwhile, I will distinguish the empty-description worklogs and handle editing description to be empty when it has assigned issue yet.

**Comment by mikx98** [comment]
However, bear in mind that preventing of assigning issues from the sidebar may not be enough, since you can assign issue via key shortcuts only.

**Comment by domiin50** [comment]
> However, bear in mind that preventing of assigning issues from the sidebar may not be enough since you can assign issue via key shortcuts only.

Okay, I amended the commit in #190 and added handling of issue assigning to no-description worklogs.
