### ISSUE TITLE
Ctrl+J 'Join intervals' shortcut is in specs, but does not work as advertised

### ISSUE THREAD

**Issue by MilanJimi** [vacuumlabs/fine-tracker#181]
Press `Ctrl + J` after two logs are selected (double click on them). One is deleted. On-site shortcuts don't mention this shortcut, but linked [specs](http://htmlpreview.github.io/?https://github.com/vacuumlabs/fine-tracker/blob/master/spec/dist/index.html) do.

One should be updated

**Comment by mikx98** [comment]
Join of n consequent intervals should remove the inner n-1 intervals (not the first one). I am not sure whether join functionality is migrated into the new design or not - @domiin50 (?). I agree that if it is supported, we should show the key shortcut.

**Comment by domiin50** [comment]
It is supported. All selected work logs are merged into one as it is implemented in the beta version.
I will add this functionality to shortcuts overview.
