### ISSUE TITLE
Deleting ongoing log with an older one crashes the app

### ISSUE THREAD

**Issue by MilanJimi** [vacuumlabs/fine-tracker#182]
1. Create a log and an ongoing one (one that ends with `Now`)
2. Delete the `Now` log with an older one (select them with double click)
3. You'll get `TypeError: "e[(t - 1)] is undefined"`

The same error as in https://github.com/vacuumlabs/fine-tracker/issues/175. Related?

**Comment by domiin50** [comment]
I was not able to reproduce this error.
1. I had open the FineTracker in an incognito window and login - no points in local storage
2. Created 2 logs one after another - the second one is ongoing (with `Now`)
3. Selected both of them with double click
4. Deleted selection with `Delete` key

Everything went right and both of worklogs have been deleted. It remained no more logs in overview and timeline.

@mikx98, are u able to reproduce this??

**Comment by mikx98** [comment]
Neither I am able to reproduce it.
@MilanJimi please collaborate on finding out how exactly you reproduced it. A video would be perfect.
