### ISSUE TITLE
After submitting, I can no longer delete / change time unsubmitted logs

### ISSUE THREAD

**Issue by MilanJimi** [vacuumlabs/fine-tracker#184]
1. Create a few logs. Assign issues to some of them and submit them
2. Try deleting a log that did NOT have an issue (and therefore was not submitted)
3. This log will not delete nor will the time be editable, even though the description will be editable

**Comment by mikx98** [comment]
Since the timeline is continuous, we can not delete a worklog that is right after a submitted worklog (it would change the end time of the submitted and hence not modifiable worklog). I believe that's the problem you are facing. However, that's expected behaviour.
