### ISSUE TITLE
Unable to log retrospectively to another day

### ISSUE THREAD

**Issue by mikx98** [vacuumlabs/fine-tracker#191]
With the current design I am not able to log retrospectively to another day. For example yesterday.

**Comment by domiin50** [comment]
You are, but it is not a user-friendly process. It can be done by shifting time with `Arrow Down` through midnight. Was this functionality even available in beta version?
@darjanin, are you able to process this functionality into the design?

**Comment by darjanin** [comment]
@mikx98  At the moment you can log to previous days by going to that day using buttons and then adding new point to specific time, right?
What about adding a date picker with date, and not only time? If you are logging through finetracker to previous days, you are not using it as it was designed - logging new points always when they happen/change.

**Comment by mikx98** [comment]
@domiin50 didn't realize that :thinking: 

@darjanin I agree that it is something that shouldn't be massively used - but for example if you work across midnight, you may want to log something that you started doing 23:45 at 0.04. Typing in 23:45 would add it 24 hours later. So I would suggest implementing at least _some_ intuitive solution - for example that date picker.

**Comment by mikx98** [comment]
and NO you can not go to that day in worklogs (like navigating through worklogs, then creating a new worklog), right now you can log to another day by going across midnight in the time picker (by keyboard arrows only).

**Comment by jakuub** [comment]
I know, that fine-tracker wasn't built for this, but for example me, I use it mostly this way. It also wasn't built for "clickable" mode :-). 

Please, add some possibility to do retrospective logging easy, even if it is just for me :pray:
