### ISSUE TITLE
New mode for submiting

### ISSUE THREAD

**Issue by jakuub** [vacuumlabs/fine-tracker#205]
Move submitting to Jira to separate mode, rendered instead of agenda.

**Comment by darjanin** [comment]
Ignore the differences in the header and input field.

- [ ] In the JIRA panel hide options and show only description why it's not available. (Feel free to change text.)
- [ ] Disable input fields at the bottom when a user is in the submit mode.
- [ ] Group items using their JIRA task number, and sort the in their group by date. (If the date format shown in the image is different from current version of the Finetracker, then use the one from the app, and not from the design).
- [ ] List of the items before submit needs be scrollable by mouse and by cursor arrows, you just cannot interact with items.

![Desktop HD submitting](https://user-images.githubusercontent.com/2865988/66760581-b3ca4100-eea2-11e9-96d0-5f61a8494737.png)
