### ISSUE TITLE
Time from older on top to the newest on the bottom in new design

### ISSUE THREAD

**Issue by jakuub** [vacuumlabs/fine-tracker#225]
The order of agenda looks contra-intuitive to me, I would prefer to have it in reverse - to have newest thing on the bottom, right above the input field. 

Let's discuss this with @darjanin

**Comment by mikx98** [comment]
personally I am used to the current order and can only hardly imagine having it reversed, but I am open for discussion :)

**Comment by domiin50** [comment]
@jakuub Should we plan a meeting for the next week? This actual one is probably for many of us full due to ReactiveConf.

**Comment by domiin50** [comment]
According to the meeting, this will be done.
Rotate the order of the worklogs in the overview.
Also, do some more changes according this overview #240, #241.
