### ISSUE TITLE
Change the date pursuant to the highest displayed log

### ISSUE THREAD

**Issue by domiin50** [vacuumlabs/fine-tracker#230]
Implement changing of the displayed date in the worklogs overview header pursuant to the log that is actually displayed on the top of the agenda.

Maybe use [React Waypoint library](https://www.npmjs.com/package/react-waypoint) or a native HTML event handling.

**Comment by FrantisekMichalSebestyen** [comment]
Closing #230 #231 and #232 as decided on design meeting.
Timeline and displayed date will change according to the currently selected log.
