### ISSUE TITLE
Add undo and redo buttons

### ISSUE THREAD

**Issue by FrantisekMichalSebestyen** [vacuumlabs/fine-tracker#243]
Add undo and redo buttons, so user can move through history using buttons.
As far as I remeber we aggreed to put these buttons next to the displayed date on header.

**Comment by mikx98** [comment]
afaik we agreed to put the icons on the top right of worklogs container (below timeline & header, left of issue sidebar)

**Comment by FrantisekMichalSebestyen** [comment]
Should we create new bar with only these 2 buttons ? Since we moved displayed date.
