### ISSUE TITLE
Show shortcuts as default, save customer preference

### ISSUE THREAD

**Issue by mikx98** [vacuumlabs/fine-tracker#295]
Shortcuts should be displayed by default (e.g. it is useful for a new user coming in, that doesn't know finetracker at all). Also, we don't want to irritate people that know the shortcuts already.

Supposed solution: store the show/hide shortcuts in redux and set to autosync with localstorage (as we do with e.g. points property)

**Comment by jakuub** [comment]
I don't think we need that. All interface is clickable and there should be no action which is not clickable. 

Users will most of the time start to use it by clicking, and then they will slowly switch to shortcuts. 
And they are visible enough. 

More important would be some guide/tutorial/whatever what will tell them, how to use it.

**Comment by mikx98** [comment]
@jakuub okay, agree .. I never used the clicking approach, so that's probably why I wanted to force people into using shortcuts :smile: let's close this one then
