### ISSUE TITLE
Time is offset after exporting to Jira

### ISSUE THREAD

**Issue by pepsin92** [vacuumlabs/fine-tracker#325]
After exporting, tasks in Jira are offset by 1 hour, e.g. task logged in fine-tracker at 9:30 appears to start at 8:30 in Jira.

**Comment by radoh** [comment]
I think this is a duplicate of https://github.com/vacuumlabs/fine-tracker/issues/93

**Comment by pepsin92** [comment]
You're correct! @pepsin92 out!
