### ISSUE TITLE
Add tips for useful non-intuitive operations

### ISSUE THREAD

**Issue by mikx98** [vacuumlabs/fine-tracker#46]
for example:

- near input, there would be tip saying that you can go through history of worklogs by key up/down
- in input when joining intervals you can also go through worklogs, but just the ones relevant (worklogs of selected intervals)
- when current task is taking too long, there is possibility that the person got away from the computer and he would likely want to split the interval somehow - show a tip that with ctrl + Enter he can log point with custom time
- whatever is not intuitive for you :)

**Comment by Siegrift** [comment]
Btw. I would like the autocomplete to suggest things as I type (similar to autocomplete in editors). And I would be glad if the descriptions are persisted (not erased after submitting)

**Comment by mikx98** [comment]
will come with the new design
