### ISSUE TITLE
Converted spec is not being updated

### ISSUE THREAD

**Issue by Siegrift** [vacuumlabs/fine-tracker#49]
The [converted spec](http://htmlpreview.github.io/?https://github.com/vacuumlabs/fine-tracker/blob/master/spec/dist/index.html) is not being updated after making changes to [raw spec](https://github.com/vacuumlabs/fine-tracker/blob/master/spec/src/index.adoc)

**Comment by hleumas** [comment]
Yeah, it is not done automatically. You need to run the guard to build it.

**Comment by Siegrift** [comment]
@hleumas can you give instructions how to do that?

**Comment by hleumas** [comment]
Install ruby. Install bundler. Then I believe:

```
bundle
guard
touch index.adoc # guard monitors changes, so you need to make some change while it's running
```
