### ISSUE TITLE
Add settings

### ISSUE THREAD

**Issue by mikx98** [vacuumlabs/fine-tracker#77]
Open settings by clicking on avatar image.
They would contain at least: Help, Speed dial settings, Logout and Rounding enabled/disabled.

**Comment by domiin50** [comment]
@mikx98 still relevant in the new design? WDYT? IMO, there is no need of dropdown because there are several icons for these functionalities.

**Comment by mikx98** [comment]
@domiin50 I think that the proposed options are all covered by the new design. Maybe we can think of some other customizable options, though. Till then, imo we can close this
