### ISSUE TITLE
Fit to screen height

### ISSUE THREAD

**Issue by jakuub** [vacuumlabs/fine-tracker#91]
It is a little bit strange, to have duplicate srollbars. It will be perfect, if header is fixed to the top, and whole page is scrolling the calendar content. Or some other way - I don't care much about implementation, but current state is not very user friendly.

Small screen:
![image](https://user-images.githubusercontent.com/1863153/50770884-1eea4580-1289-11e9-91f0-7bbb02a99f4e.png)
Big screen:
![image](https://user-images.githubusercontent.com/1863153/50770953-5953e280-1289-11e9-8962-aa91597838fe.png)
(i included my botton ubuntu bar to be able to see the empty space)

**Comment by misogl** [comment]
This is really annoying. I have 1/4 of the screen blank and I have to scroll through the logs.
