### ISSUE TITLE
Show only a portion of day in submit summary

### ISSUE THREAD

**Issue by jakuub** [vacuumlabs/fine-tracker#92]
We can start at 08:00 and end at 18:00 for example, if logs don't exist outside of this range.
![image](https://user-images.githubusercontent.com/1863153/50771241-54dbf980-128a-11e9-8612-703ce0cf804b.png)

**Comment by mikx98** [comment]
right now, we don't show the calendar in the submit dialog.
moreover, it will totally change with the upcoming new design, such that this problem will be solved for free (agenda confirmation view)
