### ISSUE TITLE
smarter JIRA issue search

### ISSUE THREAD

**Issue by hleumas** [vacuumlabs/fine-tracker#94]
Search should not be sensitive to a word order, i.e. `project management` and `management project` should be considered match.

This is especially important when searching for issues that contain similar words in multiple projects. In such a case, one would really like to use query like `WOR project management` to search for project managament task on wordy project.

The simple solution is to:

* split by words both needle and haystack
* the match is considered when each word of needle is a prefix of some word in a result

**Comment by jakuub** [comment]
@hleumas do you think this should be done before the presentation of the project on Vacuum talk? If so, I will add it to milestone 1.0 - I added it for this purpose, to track issues needed to be completed before we show it to the rest of the Vacuum.

**Comment by hleumas** [comment]
I think this is quick and easy to implement and really valuable feature. Actually, one of the most sucking things on Tempo is the search that doesn't work properly.

**Comment by jakuub** [comment]
OK, I am adding it to milestone 1.0 :-). 
To be honest, I didn't check the implementation and therefore can't estimate the complexity of this issue.
